### ISSUE TITLE
Error while connecting from gremlin (constructor?)

### ISSUE THREAD

**Issue by MartinBrugnara** [arangodb/blueprints-arangodb-graph#22]
Software versions:
- Gremlin: 2.6
- blueprints-arangodb-graph: 1.0.13
- arangodb: 2.7.7 & 2.8.7 (tested both)

Gremlin (groovy) script: 
```
import com.arangodb.blueprints.ArangoDBGraph
g = new ArangoDBGraph("arango", 8529, "G", "V", "E"); 
// arango: entry in hosts file with the IP of the server
```

env (using your docker image to run the server):
- ARANGO_NO_AUTH=1

Result 
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/gremlin-groovy-2.6.0/lib/logback-classic-0.9.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/gremlin-groovy-2.6.0/lib/slf4j-log4j12-1.7.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
        at com.arangodb.http.HttpManager.initSSLConnectionSocketFactory(HttpManager.java:674)
        at com.arangodb.http.HttpManager.init(HttpManager.java:120)
        at com.arangodb.ArangoConfigure.init(ArangoConfigure.java:296)
        at com.arangodb.blueprints.client.ArangoDBSimpleGraphClient.<init>(ArangoDBSimpleGraphClient.java:67)
        at com.arangodb.blueprints.ArangoDBGraph.<init>(ArangoDBGraph.java:155)
        at com.arangodb.blueprints.ArangoDBGraph.<init>(ArangoDBGraph.java:121)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
        at Script1.run(Script1.groovy:12)
        at com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:231)
        at com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:102)
        at com.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:97)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:212)
        at com.tinkerpop.gremlin.groovy.jsr223.ScriptExecutor.evaluate(ScriptExecutor.java:36)
        at com.tinkerpop.gremlin.groovy.jsr223.ScriptExecutor.main(ScriptExecutor.java:20)
```

**Comment by dothebart** [comment]
Can you by any chance provide the actual http request? via wireshark or ngrep?

**Comment by MartinBrugnara** [comment]
Sure, as soon as I am back to office..

**Comment by MartinBrugnara** [comment]
Checked: it seams no data reaches the server.

The problem is not in the machine connection, because if I use ping or wget it works.
But if I use gremlin, I get always the same error.
As confirm of this the server status page does not report any additional activity when I try to run connect (from gremlin).

**Comment by MartinBrugnara** [comment]
Following the stack trace it seams to me that the java driver does not check whether or not we need SSL
(by default and in my case not).

Relevant lines:
- https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/ArangoConfigure.java#L296
- https://github.com/arangodb/arangodb-java-driver/blob/master/src/main/java/com/arangodb/http/HttpManager.java#L115
  (to L124)

**Comment by a-brandt** [comment]
I think this is a problem of two different versions of httpcore or httpclient. 

The ArangoDB java client uses version 4.5.1 of the apache HTTP client (httpcore 4.4.3) and gremlin uses an older version (4.2.5 with httpcore 4.2.4).

**Comment by MartinBrugnara** [comment]
@a-brandt Thank you for checking out,
I'am a noob in the java ecosystem, do you have any suggestion on how I can hack this thing to work?

**Comment by a-brandt** [comment]
I make a branch of the arangodb-java-driver and change the http client version to 4.2.5.

**Comment by a-brandt** [comment]
I released version 1.0.14. Please retry with the new version.

**Comment by MartinBrugnara** [comment]
It fails building with the following error:
```Failed to execute goal on project blueprints-arangodb: Could not resolve dependencies for project my-project:blueprints-arangodb:pom:2.7.3: Could not find artifact com.arangodb:arangodb-java-driver:jar:2.6.10```

Looking at ```http://mvnrepository.com/artifact/com.arangodb/arangodb-java-driver``` it seams 2.6.10 does not exists (yet), even tough it does on the github repo.

I suppose I should just wait for maven to 'propagate' the updated index, right?

**Comment by a-brandt** [comment]
Yes, I think we have to wait.

**Comment by a-brandt** [comment]
2.6.10 is available here: [http://search.maven.org](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.arangodb%22%20AND%20a%3A%22arangodb-java-driver%22)

**Comment by MartinBrugnara** [comment]
It compiles and connect know,
thank you so much!
